### PR TITLE
Top bar

### PR DESCRIPTION
**Pull request by CollinWoo**
This implements the top bar of the main UI

### CODE REVIEW

**Comment by wizhaaa** [comment]
Could you remove any unused state variables to pass the checks?

**Comment by CollinWoo** [comment]
Could I get access to preview deployments? I didn't know what the issue was because I couldn't access it.

**Comment by wizhaaa** [comment]
The CI pipeline also shows the errors (aka when you run yarn build) it should tell you any errors.

**Comment by wizhaaa** [comment]
> Could I get access to preview deployments? I didn't know what the issue was because I couldn't access it.

I can't add as I don't have vercel premium T.T rip

**Comment by wizhaaa** [comment]
image

image

Are you able to fix the dropdown part here too?

**Comment by CollinWoo** [comment]
I don't think the base html `select` element can be restyled like that... I could use a UI library but that might be overkill

**Comment by CollinWoo** [comment]
I could use a UI library but that might be overkill

**Comment by wizhaaa** [comment]
> I don't think the base html `select` element can be restyled like that... I could use a UI library but that might be overkill

You could also make it a button or clickable div and add an dropdown img/icon/svg - similar to my dropdowns

**Comment by CollinWoo** [comment]
imo, it might be better to use a UI library going forward. Since we're short on time, I think styling pre-implemented components instead of creating our own might be quicker (especially for something like a dropdown) and taking a more opinionated approach with well defined interfaces will mean we spend less time thinking about different ways of doing things. What do you think?

**Comment by wizhaaa** [comment]
I think a UI library is lowkey overkill for a 1 page interface. Just creating a simple dropdown is pretty trivial i think - if we use a UI library it won't be fully accurate to the designs given 

+ takes time to learn a UI library 
+ customizing a UI library component to look like our designs can be a struggle 
+ UI libraries inject some CSS too that overwrites some of our own CSS too 

But that is also just my opinion as I'm pretty against UI libraries if we don't necessarily need it

**Review by wizhaaa — APPROVED** [review]
Thanks so much Colin on working on this issue. I know ts and all this stuff is pretty annoying to work with! Thanks for sticking with it!

**Pull request merged**
